/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exec;

import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import javax.swing.*;
import modele.element.Arme;
import modele.element.Armure;
import modele.element.Aventure;
import modele.element.Nourriture;
import modele.element.Objet;
import modele.element.Personnage;
import modele.element.Poison;
import modele.element.Porte;

/**
 *
 * @author pierrecharbit
 */
public class AppliGraphique extends javax.swing.JFrame {
    Aventure aventure;
    boolean visible = false;
    int poids_inventaire = 0;
    //int poids_max = 10;
    
    
    /**
     * Creates new form AppliGraphique
     */
    public AppliGraphique() {
        initComponents();
        this.aventure = new Aventure();
    }
    
    public AppliGraphique(Aventure aventure) {
        this.aventure = aventure;
        
        initComponents();
        
        Panneau_heros.setVisible(false);
        
        mise_a_jour();
        
        this.pack();
        //debut();
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nomperso = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        descriptionperso = new javax.swing.JTextField();
        forceperso = new javax.swing.JSlider();
        agiliteperso = new javax.swing.JSlider();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jouer = new javax.swing.JButton();
        afficheforce = new javax.swing.JTextField();
        afficheagilite = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jFrame2 = new javax.swing.JFrame();
        Panneau_recit = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        Panneau_entree = new javax.swing.JPanel();
        Entree = new javax.swing.JTextField();
        panneau_combat = new javax.swing.JPanel();
        frapper = new javax.swing.JButton();
        jList1 = new javax.swing.JList<>();
        panneau_porte = new javax.swing.JPanel();
        porte = new javax.swing.JButton();
        jList2 = new javax.swing.JList<>();
        panneau_objet = new javax.swing.JPanel();
        ramasser = new javax.swing.JButton();
        jList3 = new javax.swing.JList<>();
        fiche = new javax.swing.JButton();
        Panneau_heros = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        utiliser = new javax.swing.JButton();
        jeter = new javax.swing.JButton();
        retirer = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jProgressBar2 = new javax.swing.JProgressBar();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jOptionPane1 = new javax.swing.JOptionPane();
        jOptionPane2 = new javax.swing.JOptionPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        debut = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jFrame1WindowClosing(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(204, 255, 204));
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(0, 102, 51));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Créez votre Personnage ");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 51));
        jLabel5.setText("Nom");

        nomperso.setText("Eric");
        nomperso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nompersoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 51));
        jLabel7.setText("Description");

        descriptionperso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionpersoActionPerformed(evt);
            }
        });

        forceperso.setForeground(new java.awt.Color(0, 102, 255));
        forceperso.setMajorTickSpacing(100);
        forceperso.setPaintLabels(true);
        forceperso.setPaintTicks(true);
        forceperso.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                forcepersoStateChanged(evt);
            }
        });
        forceperso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forcepersoMouseClicked(evt);
            }
        });

        agiliteperso.setForeground(new java.awt.Color(0, 102, 255));
        agiliteperso.setMajorTickSpacing(100);
        agiliteperso.setPaintLabels(true);
        agiliteperso.setPaintTicks(true);
        agiliteperso.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                agilitepersoStateChanged(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 51));
        jLabel8.setText("Force");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 51));
        jLabel9.setText("Agilité");

        jouer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jouer.setForeground(new java.awt.Color(0, 102, 51));
        jouer.setText("Jouer");
        jouer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jouerActionPerformed(evt);
            }
        });

        afficheforce.setEditable(false);
        afficheforce.setText("50");

        afficheagilite.setEditable(false);
        afficheagilite.setText("50");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(descriptionperso, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(49, 49, 49)
                        .addComponent(nomperso, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(agiliteperso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(afficheagilite, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(forceperso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(afficheforce, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(167, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jouer, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nomperso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(descriptionperso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(forceperso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(afficheforce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agiliteperso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(afficheagilite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jouer)
                .addGap(37, 37, 37))
        );

        jTextArea4.setEditable(false);
        jTextArea4.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea4.setColumns(20);
        jTextArea4.setForeground(new java.awt.Color(0, 51, 51));
        jTextArea4.setRows(5);
        jTextArea4.setText("Vous avez 100 points à répartir\ncomme vous le souhaitez entre\nla force et l'agilité de votre\npersonnage.");
        jTextArea4.setDisabledTextColor(new java.awt.Color(0, 51, 51));
        jScrollPane5.setViewportView(jTextArea4);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addContainerGap(386, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addGap(0, 37, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 38, Short.MAX_VALUE)))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jScrollPane5)
                .addGap(161, 161, 161))
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addGap(0, 32, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 32, Short.MAX_VALUE)))
        );

        jFrame2.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame2.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jFrame2WindowClosing(evt);
            }
        });

        Panneau_recit.setForeground(new java.awt.Color(0, 102, 51));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(204, 255, 204));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 102, 51));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Récit");

        javax.swing.GroupLayout Panneau_recitLayout = new javax.swing.GroupLayout(Panneau_recit);
        Panneau_recit.setLayout(Panneau_recitLayout);
        Panneau_recitLayout.setHorizontalGroup(
            Panneau_recitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
        );
        Panneau_recitLayout.setVerticalGroup(
            Panneau_recitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panneau_recitLayout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Entree.setEditable(false);
        Entree.setBackground(new java.awt.Color(204, 255, 204));
        Entree.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Entree.setForeground(new java.awt.Color(0, 102, 51));
        Entree.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Entree.setText("L'entrée");
        Entree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntreeActionPerformed(evt);
            }
        });

        panneau_combat.setBackground(new java.awt.Color(255, 255, 255));
        panneau_combat.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panneau_combat.setAutoscrolls(true);

        frapper.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        frapper.setForeground(new java.awt.Color(0, 102, 51));
        frapper.setText("frapper");
        frapper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frapperActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panneau_combatLayout = new javax.swing.GroupLayout(panneau_combat);
        panneau_combat.setLayout(panneau_combatLayout);
        panneau_combatLayout.setHorizontalGroup(
            panneau_combatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panneau_combatLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(frapper)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panneau_combatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panneau_combatLayout.createSequentialGroup()
                    .addGap(0, 116, Short.MAX_VALUE)
                    .addComponent(jList1)
                    .addGap(0, 116, Short.MAX_VALUE)))
        );
        panneau_combatLayout.setVerticalGroup(
            panneau_combatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panneau_combatLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(frapper)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panneau_combatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panneau_combatLayout.createSequentialGroup()
                    .addGap(0, 31, Short.MAX_VALUE)
                    .addComponent(jList1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 31, Short.MAX_VALUE)))
        );

        panneau_porte.setBackground(new java.awt.Color(255, 255, 255));
        panneau_porte.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panneau_porte.setAutoscrolls(true);

        porte.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        porte.setForeground(new java.awt.Color(0, 102, 51));
        porte.setText("emprunter la porte");
        porte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panneau_porteLayout = new javax.swing.GroupLayout(panneau_porte);
        panneau_porte.setLayout(panneau_porteLayout);
        panneau_porteLayout.setHorizontalGroup(
            panneau_porteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panneau_porteLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(porte)
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(panneau_porteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panneau_porteLayout.createSequentialGroup()
                    .addGap(0, 140, Short.MAX_VALUE)
                    .addComponent(jList2)
                    .addGap(0, 140, Short.MAX_VALUE)))
        );
        panneau_porteLayout.setVerticalGroup(
            panneau_porteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panneau_porteLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(porte)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panneau_porteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panneau_porteLayout.createSequentialGroup()
                    .addGap(0, 29, Short.MAX_VALUE)
                    .addComponent(jList2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 29, Short.MAX_VALUE)))
        );

        panneau_objet.setBackground(new java.awt.Color(255, 255, 255));
        panneau_objet.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panneau_objet.setAutoscrolls(true);
        panneau_objet.setPreferredSize(new java.awt.Dimension(160, 158));

        ramasser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ramasser.setForeground(new java.awt.Color(0, 102, 51));
        ramasser.setText("ramasser");
        ramasser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ramasserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panneau_objetLayout = new javax.swing.GroupLayout(panneau_objet);
        panneau_objet.setLayout(panneau_objetLayout);
        panneau_objetLayout.setHorizontalGroup(
            panneau_objetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panneau_objetLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(ramasser)
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(panneau_objetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panneau_objetLayout.createSequentialGroup()
                    .addGap(0, 134, Short.MAX_VALUE)
                    .addComponent(jList3)
                    .addGap(0, 134, Short.MAX_VALUE)))
        );
        panneau_objetLayout.setVerticalGroup(
            panneau_objetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panneau_objetLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ramasser)
                .addContainerGap())
            .addGroup(panneau_objetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panneau_objetLayout.createSequentialGroup()
                    .addGap(0, 32, Short.MAX_VALUE)
                    .addComponent(jList3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 32, Short.MAX_VALUE)))
        );

        fiche.setBackground(new java.awt.Color(204, 255, 204));
        fiche.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fiche.setForeground(new java.awt.Color(0, 102, 51));
        fiche.setText("Afficher fiche héros");
        fiche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ficheActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 51));
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 51));
        jLabel2.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 51));
        jLabel3.setText("jLabel3");

        jScrollPane1.setViewportView(null);

        jList4.setForeground(new java.awt.Color(0, 102, 51));
        jScrollPane1.setViewportView(jList4);

        utiliser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        utiliser.setForeground(new java.awt.Color(0, 102, 51));
        utiliser.setText("utiliser");
        utiliser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utiliserActionPerformed(evt);
            }
        });

        jeter.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jeter.setForeground(new java.awt.Color(0, 102, 51));
        jeter.setText("jeter");
        jeter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jeterActionPerformed(evt);
            }
        });

        retirer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        retirer.setForeground(new java.awt.Color(0, 102, 51));
        retirer.setText("retirer");
        retirer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retirerActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 51));
        jLabel4.setText("jLabel4");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 51));
        jLabel6.setText("jLabel6");

        jProgressBar2.setStringPainted(true);

        javax.swing.GroupLayout Panneau_herosLayout = new javax.swing.GroupLayout(Panneau_heros);
        Panneau_heros.setLayout(Panneau_herosLayout);
        Panneau_herosLayout.setHorizontalGroup(
            Panneau_herosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panneau_herosLayout.createSequentialGroup()
                .addGroup(Panneau_herosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panneau_herosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Panneau_herosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panneau_herosLayout.createSequentialGroup()
                                .addGroup(Panneau_herosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(52, 52, 52))
                            .addComponent(jLabel6)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panneau_herosLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)))
                .addGroup(Panneau_herosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panneau_herosLayout.createSequentialGroup()
                        .addGroup(Panneau_herosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panneau_herosLayout.createSequentialGroup()
                                .addGap(355, 355, 355)
                                .addComponent(utiliser, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jeter, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(retirer, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Panneau_herosLayout.createSequentialGroup()
                                .addGap(333, 333, 333)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panneau_herosLayout.createSequentialGroup()
                        .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141))))
        );
        Panneau_herosLayout.setVerticalGroup(
            Panneau_herosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panneau_herosLayout.createSequentialGroup()
                .addGroup(Panneau_herosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Panneau_herosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panneau_herosLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addGroup(Panneau_herosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(retirer)
                            .addComponent(jeter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(utiliser))
                        .addGap(71, 71, 71))
                    .addGroup(Panneau_herosLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout Panneau_entreeLayout = new javax.swing.GroupLayout(Panneau_entree);
        Panneau_entree.setLayout(Panneau_entreeLayout);
        Panneau_entreeLayout.setHorizontalGroup(
            Panneau_entreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panneau_entreeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panneau_entreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panneau_heros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Panneau_entreeLayout.createSequentialGroup()
                        .addComponent(panneau_objet, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panneau_porte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panneau_combat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Panneau_entreeLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(fiche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(Entree)
        );
        Panneau_entreeLayout.setVerticalGroup(
            Panneau_entreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panneau_entreeLayout.createSequentialGroup()
                .addComponent(Entree)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Panneau_entreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panneau_porte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panneau_combat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panneau_objet, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fiche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Panneau_heros, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panneau_recit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panneau_entree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(Panneau_recit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(Panneau_entree, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));

        debut.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        debut.setForeground(new java.awt.Color(0, 102, 51));
        debut.setText("Commencer une partie");
        debut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debutActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(0, 0, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Jeu de Eric et Laura");

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(0, 102, 51));
        jTextArea3.setRows(5);
        jTextArea3.setText("Bonjour, bienvenue dans notre Donjon.\nTrouvez la sortie sans vous faire tuer.\nBonne chance!");
        jTextArea3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea3.setCaretColor(new java.awt.Color(0, 102, 51));
        jScrollPane4.setViewportView(jTextArea3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(debut, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addGap(76, 76, 76)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(debut, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void emplacement(){
        Panneau_entree.setLayout(new GridLayout(1,3));
    }
    
    
    private void EntreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntreeActionPerformed

    private void frapperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frapperActionPerformed
        // TODO add your handling code here:
        Personnage ennemi = jList1.getSelectedValue();
        String s = aventure.getHeros().attaque(ennemi);
        mise_a_jour();
        String t = ennemi.attaque(aventure.getHeros());
        jTextArea1.append(s+"\n"+t+"\n");
        if (ennemi.getVie() <=0){
            jTextArea1.append("Bravo vous avez tué un " + ennemi+".\n");
            aventure.getHeros().getLieu().monstres.remove(ennemi);
        }
        
        mise_a_jour();
    }//GEN-LAST:event_frapperActionPerformed

    private void porteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porteActionPerformed
        // TODO add your handling code here:
      
        /*
        List<Porte> p = aventure.getHeros().getLieu().getListePortes();
        DefaultListModel<Porte> lp = new DefaultListModel<>();
        lp.addAll(p);
        jList2.setModel(lp);
        */
        //update_porte();
        Porte portee = jList2.getSelectedValue();
        aventure.getHeros().empruntePorte(portee);
        jTextArea1.append(aventure.getHeros() + " a emprunté la porte " + portee.num + ".\n");
        jTextArea1.append(aventure.getHeros() + " vient d'arriver dans la " + aventure.getHeros().getLieu() + ".\n");
        mise_a_jour();
    }//GEN-LAST:event_porteActionPerformed

    private void ramasserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ramasserActionPerformed
        // TODO add your handling code here:
        Objet outil = jList3.getSelectedValue();
        
        if (poids_inventaire + outil.getPoids() > aventure.getHeros().getPoids_max()){
            jTextArea1.append("Votre sac est trop chargé, veuillez l'alléger pour pouvoir ramasser d'autres objets.\n");
        }
        else{
            aventure.getHeros().getInventaire().add(outil);
            aventure.getHeros().getLieu().objets.remove(outil);
            poids_inventaire += outil.poids;
            jProgressBar2.setValue(poids_inventaire*10);
            jTextArea1.append(aventure.getHeros() + " a ramassé un " + outil + ".\n");
        }
        
        mise_a_jour();
    }//GEN-LAST:event_ramasserActionPerformed

    private void utiliserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utiliserActionPerformed
        // TODO add your handling code here:
        Objet outil = jList4.getSelectedValue();
    
        if (outil instanceof Arme){
            aventure.getHeros().equipe((Arme) outil);
            jTextArea1.append(aventure.getHeros() + " s'est équipé de " + outil + ".\n");
        }
        if (outil instanceof Armure){
           aventure.getHeros().equipe((Armure) outil);
           jTextArea1.append(aventure.getHeros() + " a mis une " + outil + ".\n");
        }
        if (outil instanceof Nourriture){
           aventure.getHeros().mange((Nourriture) outil);
           aventure.getHeros().getInventaire().remove(outil);
           poids_inventaire -= outil.poids;
           jProgressBar2.setValue(poids_inventaire*10);
           jTextArea1.append(aventure.getHeros() + " a mangé un " + outil + " et a gagné "+ ((Nourriture) outil).points_gagnes +" points de vie.\n");
        }
        
        if (outil instanceof Poison){
            poids_inventaire -= outil.poids;
           aventure.getHeros().mange((Poison) outil);
           aventure.getHeros().getInventaire().remove(outil);
           poids_inventaire -= outil.poids;
           jProgressBar2.setValue(poids_inventaire*10);
           jTextArea1.append(aventure.getHeros() + " a mangé un " + outil + "\n" + "Oups, c'était un poison, " + aventure.getHeros().effetpoison((Poison) outil)+ ".\n");
        }
        
        mise_a_jour();
    }//GEN-LAST:event_utiliserActionPerformed

    private void jeterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jeterActionPerformed
        // TODO add your handling code here:
        Objet outil = jList4.getSelectedValue();
        poids_inventaire -= outil.poids;
        jProgressBar2.setValue(poids_inventaire*10);
        aventure.getHeros().getInventaire().remove(outil);
        jTextArea1.append(aventure.getHeros() + "a jeté un " + outil + ".\n");
        mise_a_jour();
    }//GEN-LAST:event_jeterActionPerformed

    private void retirerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retirerActionPerformed
        // TODO add your handling code here:
        Objet outil = jList4.getSelectedValue();
        if (outil instanceof Arme){
            Arme a = new Arme();
            aventure.getHeros().setArme(a);
            jTextArea1.append(aventure.getHeros() + "a retiré " + outil + ".\n");
        }
        if (outil instanceof Armure){
           Armure a = new Armure();
           aventure.getHeros().setArmure(a);
           jTextArea1.append(aventure.getHeros() + "a retiré " + outil + ".\n");
        }
        mise_a_jour();
    }//GEN-LAST:event_retirerActionPerformed

    private void ficheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ficheActionPerformed
        // TODO add your handling code here:
        if (this.visible == true){
            
            Panneau_heros.setVisible(false);
            fiche.setText("Afficher fiche héros");
            this.visible = false;
        }
        else{
            
            Panneau_heros.setVisible(true);
            fiche.setText("Masquer fiche héros");
            this.visible = true;
        }
        this.pack();
    }//GEN-LAST:event_ficheActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void nompersoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nompersoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nompersoActionPerformed

    private void descriptionpersoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionpersoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionpersoActionPerformed

    private void jouerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jouerActionPerformed
        // TODO add your handling code here:
        aventure.getHeros().setNom(nomperso.getText());
        
        aventure.getHeros().setDescription(descriptionperso.getText());
        int a = forceperso.getValue();
        int b = agiliteperso.getValue();
        if(a+b<=100){
            aventure.getHeros().setForce(forceperso.getValue());
            aventure.getHeros().setAgilite(agiliteperso.getValue());
            mise_a_jour();
            jFrame1.setVisible(false);
            jFrame2.setVisible(true);
            jFrame2.pack();
            jTextArea1.append(aventure.getHeros().getNom() + " vient d'arriver dans la première salle du donjon.\n");
        }
        
    }//GEN-LAST:event_jouerActionPerformed

   
    
    private void debutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debutActionPerformed
        // TODO add your handling code here:
       this.setVisible(false);
       jFrame1.setVisible(true);
       jFrame1.pack();
    }//GEN-LAST:event_debutActionPerformed

    private void forcepersoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forcepersoMouseClicked
        // TODO add your handling code here:
        String s = ""+forceperso.getValue();
        afficheforce.setText(s);
    }//GEN-LAST:event_forcepersoMouseClicked

    private void forcepersoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_forcepersoStateChanged
        // TODO add your handling code here:
        afficheforce.setText(Integer.toString(forceperso.getValue()));
    }//GEN-LAST:event_forcepersoStateChanged

    private void agilitepersoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_agilitepersoStateChanged
        // TODO add your handling code here:
        afficheagilite.setText(Integer.toString(agiliteperso.getValue()));
    }//GEN-LAST:event_agilitepersoStateChanged

    private void jFrame2WindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrame2WindowClosing
        // TODO add your handling code here:
        int reponse = JOptionPane.showConfirmDialog(jFrame2, "Etes-vous sur de vouloir abandonner ?", "Quitter", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(reponse == JOptionPane.YES_OPTION){
            //dispose();
            //jFrame2.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            //System.exit(0);
            jFrame2.setVisible(false);
            this.setVisible(true);
        }
        jFrame2.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }//GEN-LAST:event_jFrame2WindowClosing

    private void jFrame1WindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrame1WindowClosing
        // TODO add your handling code here: 
    }//GEN-LAST:event_jFrame1WindowClosing

    
    
    public void fiche_heros(){
        jLabel1.setText("Force : " + aventure.getHeros().getForce());
        jLabel2.setText("Agilite : " + aventure.getHeros().getAgilite());
        jLabel3.setText("Vie : " + aventure.getHeros().getVie());
        jLabel4.setText("Arme : " + aventure.getHeros().arme);
        jLabel6.setText("Armure : " + aventure.getHeros().armure);
    }
    
    public void update_ennemis(){
        DefaultListModel<Personnage> ennemi = new DefaultListModel<>();
        ennemi.addAll(aventure.getHeros().getLieu().getMonstres());
        jList1.setModel(ennemi);
    }
    
    public void update_objets(){
        DefaultListModel<Objet> outils = new DefaultListModel<>();
        outils.addAll(aventure.getHeros().getLieu().getObjets());
        jList3.setModel(outils);
    }
    
    public void update_porte(){
        DefaultListModel<Porte> porte = new DefaultListModel<>();
        porte.addAll(aventure.getHeros().getLieu().getListePortes());
        jList2.setModel(porte);
    }
    
    public void update_inventaire(){
        DefaultListModel<Objet> inventaire = new DefaultListModel<>();
        inventaire.addAll(aventure.getHeros().getInventaire());
        jList4.setModel(inventaire);
    }
    
    public void mort(){
       if (aventure.getHeros().getVie() <= 0){
           /*int reponse = JOptionPane.showMessageDialog(jFrame2,"Vous etes mort", "Fin", JOptionPane.DEFAULT_OPTION);
           if (reponse == JOptionPane.CLOSED_OPTION){
               System.exit(0);
           }*/
           String textes[]= {"revenir au menu principal", "quittez l'application"};
           int retour = JOptionPane.showOptionDialog(jFrame2, "Aïe, vous etes mort !", "Fin", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, textes, textes[0]);
           if(retour == JOptionPane.CLOSED_OPTION){
               //System.exit(0);
               jFrame2.setVisible(false);
               this.setVisible(true);
           }
           else if(retour == JOptionPane.YES_OPTION){
               jFrame2.setVisible(false);
               this.setVisible(true);
           }
           else{
               System.exit(0);
           }
           
       }
        
    }
    
    public void debut(){
        jTextArea1.append(aventure.getHeros().getNom() + " vient d'arriver dans la première salle du donjon.\n");
        
    }
    
    public void fin(){
        if (aventure.getHeros().getLieu() == aventure.getDecor().arrivee){
            String textes[]= {"revenir au menu principal", "quittez l'application"};
           int retour = JOptionPane.showOptionDialog(jFrame2, "BRAVOOO, vous avez trouvé la sortie !", "Gagné", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, textes, textes[0]);
           if(retour == JOptionPane.CLOSED_OPTION){
               //System.exit(0);
               jFrame2.setVisible(false);
               this.setVisible(true);
           }
           else if(retour == JOptionPane.YES_OPTION){
               jFrame2.setVisible(false);
               this.setVisible(true);
           }
           else{
               System.exit(0);
           }
        }
    }
    
    public void mise_a_jour(){
        mort();
        fin();
        fiche_heros();
        update_ennemis();
        update_objets();
        update_porte();
        update_inventaire();
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppliGraphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppliGraphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppliGraphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppliGraphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppliGraphique().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Entree;
    private javax.swing.JPanel Panneau_entree;
    private javax.swing.JPanel Panneau_heros;
    private javax.swing.JPanel Panneau_recit;
    private javax.swing.JTextField afficheagilite;
    private javax.swing.JTextField afficheforce;
    private javax.swing.JSlider agiliteperso;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton debut;
    private javax.swing.JTextField descriptionperso;
    private javax.swing.JButton fiche;
    private javax.swing.JSlider forceperso;
    private javax.swing.JButton frapper;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<Personnage> jList1;
    private javax.swing.JList<Porte> jList2;
    private javax.swing.JList<Objet> jList3;
    private javax.swing.JList<Objet> jList4;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JOptionPane jOptionPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton jeter;
    private javax.swing.JButton jouer;
    private javax.swing.JTextField nomperso;
    private javax.swing.JPanel panneau_combat;
    private javax.swing.JPanel panneau_objet;
    private javax.swing.JPanel panneau_porte;
    private javax.swing.JButton porte;
    private javax.swing.JButton ramasser;
    private javax.swing.JButton retirer;
    private javax.swing.JButton utiliser;
    // End of variables declaration//GEN-END:variables
}
